// Question templates organized by detected document type

export const QUESTION_TEMPLATES: Record<string, string[]> = {
  Legal: [
    "Who are the parties involved in this agreement?",
    "What are the key terms and obligations of each party?",
    "What are the termination clauses and conditions?",
    "What penalties or liabilities are defined?",
    "What is the governing law and jurisdiction?",
    "What are the payment terms and amounts?",
    "Are there any non-compete or confidentiality clauses?",
    "What is the effective date and duration of this agreement?",
  ],
  Medical: [
    "What is the diagnosis or medical condition described?",
    "What medications or treatments are prescribed?",
    "What are the recommended dosages and instructions?",
    "What follow-up appointments or tests are required?",
    "Are there any warnings or contraindications mentioned?",
    "What are the patient's vital signs or test results?",
    "What is the prognosis or expected recovery timeline?",
    "What lifestyle changes or restrictions are advised?",
  ],
  Financial: [
    "What is the total amount due or payable?",
    "What are the payment terms and due dates?",
    "What fees or charges are included?",
    "What is the account number or reference ID?",
    "Who is the payer and who is the recipient?",
    "What is the purpose or description of this transaction?",
    "Are there any discounts, penalties, or interest rates?",
    "What taxes or additional charges are applied?",
  ],
  Academic: [
    "What is the main research question or hypothesis?",
    "What methodology was used in this study?",
    "What are the key findings and conclusions?",
    "What data sources or references are cited?",
    "What limitations does the research acknowledge?",
    "What recommendations are made for future research?",
    "What is the abstract or summary of this paper?",
    "Who are the authors and what institution are they from?",
  ],
  Technical: [
    "What is the main purpose of this technical document?",
    "What are the system requirements or prerequisites?",
    "What are the key features or specifications?",
    "What are the installation or setup steps?",
    "What APIs or interfaces are documented?",
    "What error codes or troubleshooting steps are included?",
    "What are the known limitations or constraints?",
    "What version or release does this document cover?",
  ],
  Government: [
    "What is the purpose of this government document?",
    "Who issued this document and on what date?",
    "What eligibility criteria or conditions are stated?",
    "What are the applicant's details mentioned?",
    "What certificates, IDs, or reference numbers are listed?",
    "What are the terms or benefits granted?",
    "What is the validity period of this document?",
    "What authority or official has signed this document?",
  ],
  General: [
    "What is the main topic or purpose of this document?",
    "Summarize the key points mentioned.",
    "Who are the main people or organizations involved?",
    "What important dates or deadlines are mentioned?",
    "What conclusions or recommendations are made?",
    "What actions or steps are required?",
    "What evidence or data is provided to support the content?",
    "What are the most important facts in this document?",
  ],
}

export const DOC_TYPE_LABEL_MAP: Record<string, string> = {
  Legal: "Legal Contract",
  Medical: "Medical Document",
  Financial: "Financial Document",
  Academic: "Academic Paper",
  Technical: "Technical Document",
  Government: "Government Document",
  General: "General Document",
}
